### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by derekdowling** [CMPUT410W15/cmput410-project#111]
- [ ] Calls that return multiple Posts should be a list, which is done correctly, but as value corresponding to the key "posts" in the JSON object as per the spec.
- [ ] missing `GET /author/:id` call. Which should return the authors info and a list of their friends as per the spec
- [ ] Github activity is being returned within the `GET /posts` public stream call rather than purely posts

**Comment by klindenbach** [comment]
Split into #113 #114 #115 .

Please open separate issues. It's too difficult to manage otherwise.
