### ISSUE TITLE
As an author, posts I create be private to friends of friends

### ISSUE THREAD

**Issue by klindenbach** [CMPUT410W15/cmput410-project#12]

**Comment by klindenbach** [comment]
This is not implemented yet...

**Comment by klindenbach** [comment]
I don't think this is implemented. We don't do any checking for FOAFs

**Comment by NBor** [comment]
Not sure what you mean? When an Author looks at their stream, they will see posts visible to friends of friends. If they aren't a friend of a friend of a friend, they won't see those posts

**Comment by klindenbach** [comment]
Do we actually check for that? I guess I was thinking about the distributed case.

**Comment by bigchipbag** [comment]
I believe this is done. @klindenbach any other concerns?
