### ISSUE TITLE
Scale images in post instead of resizing

### ISSUE THREAD

**Issue by jsurya** [CMPUT410W15/cmput410-project#121]
![screenshot from 2015-04-04 18 57 02](https://cloud.githubusercontent.com/assets/3713143/6995319/152eff8a-dafd-11e4-8080-5a2197d4eeea.png)

**Comment by jsurya** [comment]
![image](https://cloud.githubusercontent.com/assets/3713143/6995417/97f122b6-db04-11e4-8d98-63c44f079ff3.png)

**Comment by paul80** [comment]
k i get the point

**Comment by jsurya** [comment]
@paul80 that may be a different issue. As you can see, the images are going out of the post at certain window sizes

**Comment by bigchipbag** [comment]
This is a feature - Closing.
