### ISSUE TITLE
Styling issues on Firefox?

### ISSUE THREAD

**Issue by jsurya** [CMPUT410W15/cmput410-project#122]
![image](https://cloud.githubusercontent.com/assets/3713143/6995443/5d924e72-db06-11e4-921f-9a7f6cca77e7.png)

**Comment by paul80** [comment]
found the problem, will put up a fix later on

**Comment by jsurya** [comment]
This may or may not be part of the problem... I'm documenting it here for your information

![image](https://cloud.githubusercontent.com/assets/3713143/6996223/5cfd87a2-db37-11e4-8b2c-7bd923e08812.png)

**Comment by bigchipbag** [comment]
It's picky and I think Jessica fixed this in her pull request. Closing.

**Comment by jsurya** [comment]
Never was fixed, issue still exists. I thought @paul80 had a fix for this

**Comment by paul80** [comment]
I do, it's in my pr
