### ISSUE TITLE
Author host field returning wrong address

### ISSUE THREAD

**Issue by derekdowling** [CMPUT410W15/cmput410-project#132]
The "host" field being returned with your authors is returning your root url without the appended "/api" postfix:

```
"author": {
                "url": "http://cs410.cs.ualberta.ca:41084/api/author/ 0d35e7a4d97b11e49020005056041008",
                "host": "http://cs410.cs.ualberta.ca:41084",
                "displayname": "konrad",
                "id": "0d35e7a4d97b11e49020005056041008"
            }
```

**Comment by bigchipbag** [comment]
I hope you aren't requiring our API for tomorrow's demo -> odds are nothing will be changed by 8:30 am as most of our team is gone at the moment

**Comment by bigchipbag** [comment]
Closed per Konrad's commit. Reopen if not fixed

**Comment by klindenbach** [comment]
Don't know what Ben's talking about. Fixing right now

**Comment by klindenbach** [comment]
Should be resolved
