### ISSUE TITLE
Mislabelled Foreign Author Hosts in GET /posts

### ISSUE THREAD

**Issue by derekdowling** [CMPUT410W15/cmput410-project#134]
As of 3:49PM today, I'm still seeing your guys' github activity returning as posts:
![screen shot 2015-04-08 at 3 48 16 pm](https://cloud.githubusercontent.com/assets/613964/7056174/cda117b8-de06-11e4-8c1e-d136f3044e01.png)

**Comment by paul80** [comment]
that's is not our github activity, no one on this team has a github username called djphan. one of the teams we worked with though did put his github activity inside his posts.

**Comment by derekdowling** [comment]
Alright, well in that case you're returning the wrong author host for the post because it's specified as your server.

**Comment by klindenbach** [comment]
Due date is passed. Couldn't fix if we wanted to.
