### ISSUE TITLE
Pick License

### ISSUE THREAD

**Issue by klindenbach** [CMPUT410W15/cmput410-project#3]
Anybody care?

Apache2?

**Comment by klindenbach** [comment]
Beuler?

**Comment by klindenbach** [comment]
@tbendubois @NBor @jsurya @paul80 Apache2? Objections?

**Comment by bigchipbag** [comment]
I'm fine with Apache 2

On Sun, Jan 25, 2015 at 5:36 PM, Konrad Lindenbach <notifications@github.com

**Comment by jsurya** [comment]
Apache 2 works for me too.On Sun, Jan 25, 2015 at 5:37 PM,  CMPUT410W15/cmput410-project reply@reply.github.com wrote:            I'm fine with Apache 2

On Sun, Jan 25, 2015 at 5:36 PM, Konrad Lindenbach <notifications@github.com

**Comment by NBor** [comment]
Apache 2 is good

**Comment by NBor** [comment]
btw, has anyone sent the email to Dr. Hindle yet?

**Comment by klindenbach** [comment]
Nope. Not due till Friday

**Comment by jsurya** [comment]
I sent the email just now
