### ISSUE TITLE
Submit Part 0

### ISSUE THREAD

**Issue by klindenbach** [CMPUT410W15/cmput410-project#4]
Idk.

For some reason Jessica always sends the emails.

**Comment by jsurya** [comment]
Just want to confirm I've got the right CCIDs, please reply if I've got them wrong.

@klindenbach: klindenb
@paul80: pnhan
@NBor: nborle
@tbendubois: tdubois

**Comment by jsurya** [comment]
Sent the email to the professor with our details.

**Comment by klindenbach** [comment]
But we haven't added a license yet

**Comment by jsurya** [comment]
Oops sorry, better get on that ASAP

On Wed, Jan 28, 2015 at 2:41 PM, Konrad Lindenbach <notifications@github.com

**Comment by klindenbach** [comment]
Just add an Apache2.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Jessica SuryaSent: Wednesday, January 28, 2015 2:43 PMTo: CMPUT410W15/cmput410-projectReply To: CMPUT410W15/cmput410-projectCc: Konrad LindenbachSubject: Re: [cmput410-project] Submit Part 0 (#4)Oops sorry, better get on that ASAP

On Wed, Jan 28, 2015 at 2:41 PM, Konrad Lindenbach <notifications@github.com

> wrote:
> 
> But we haven't added a license yet
> 
> —
> 
> Reply to this email directly or view it on GitHub
> 
> https://github.com/CMPUT410W15/cmput410-project/issues/4#issuecomment-71922202
> 
> .

—Reply to this email directly or view it on GitHub.
