### ISSUE TITLE
Instance Deployment

### ISSUE THREAD

**Issue by klindenbach** [CMPUT410W15/cmput410-project#57]

**Comment by bigchipbag** [comment]
I will get this done as soon as we get the information for the server instances.

**Comment by klindenbach** [comment]
From Ali:

> Hello
> In case you are using VM, Your VM is: 
> cs410-08
> Password: S26wBYSD 
> From now on, you are responsible for your password. It is recommended to change it.

**Comment by klindenbach** [comment]
VM hosting is up now.
To take a look use `ssh ccid@ohaton.cs.ualberta.ca -L8000:cs410.cs.ualberta.ca:41081`
And then navigate to `localhost:8000` in your favourite web browser
The admin user is `root` password `root`
