### ISSUE TITLE
Master currently broken

### ISSUE THREAD

**Issue by bigchipbag** [CMPUT410W15/cmput410-project#70]
Adding line 15: `url(r'^friends/', include('author.urls'))` in `/socialdistribution/urls.py` causes errors on all pages
Removing that line makes `RelatedObjectDoesNotExist` error after login or any other page access

**Comment by bigchipbag** [comment]
Exception Value: User has no author.

**Comment by klindenbach** [comment]
Alright. This is probably me

**Comment by klindenbach** [comment]
I'm not getting the `RelatedObjectDoesNotExist` error
