### ISSUE TITLE
Do commenting in-line

### ISSUE THREAD

**Issue by klindenbach** [CMPUT410W15/cmput410-project#92]
You shouldn't have to go to a separate page.

**Comment by paul80** [comment]
Yeah, just wanted the functionality down first.

**Comment by klindenbach** [comment]
Yep, no worries. Just eventually is all

**Comment by bigchipbag** [comment]
This is done -- waiting for a fix on a double commenting bug in the current pull request

**Comment by paul80** [comment]
The double commenting bug is fixed in the current one. Moved the javascript back inside home.html because moving it out results in some odd behavior but works fine when inside.

**Comment by bigchipbag** [comment]
I will get this tested sometime today

**Comment by bigchipbag** [comment]
This has been tested and fixed, also implemented in the author homepage as well and is considered closed.
